CREATE TABLE skills (
    id INT AUTO_INCREMENT NOT NULL,
    skillName VARCHAR(255) NOT NULL,
    isActive BOOLEAN DEFAULT 1 NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE priorityLevels (
    id INT AUTO_INCREMENT NOT NULL,
    levelName VARCHAR(255) NOT NULL,
    intValue SMALLINT NOT NULL,
    isActive BOOLEAN DEFAULT 1 NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE quests (
    id INT AUTO_INCREMENT NOT NULL,
    priorityLevel INT UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    expoints INT DEFAULT 1 NOT NULL ,
    isActive BOOLEAN DEFAULT 1 NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    FOREIGN KEY (priorityLevel)
      REFERENCES priorityLevels(id)
      ON UPDATE CASCADE ON DELETE RESTRICT
);